server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_attendance
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: "mykey"
  expirationMs: 86400000
